name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Test
        run: ginkgo -v ./...
